version: '3'
services:
  lint:
    image: quay.io/helmpack/chart-testing
    volumes:
      - ./:/charts
      - ./scripts:/scripts
    working_dir: /charts
    entrypoint: sh /scripts/add-repos.sh
  test:
    image: quay.io/helmpack/chart-testing
    volumes:
      - ./:/charts
    working_dir: /charts
    entrypoint: ct install --config ct.yaml
    # Note you will need to expose your kubernetes service to the container
    network_mode: host

