{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.db.fullname" . }}-direct
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.db.selectorLabels" . | nindent 4 }}
{{- end }}

