{{- if .Values.deploy.kratos.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    app.kubernetes.io/name: kratos-config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: configuration
data:
  serve_public_base_url: {{ include "ztka.consoleFQDNWithScheme" . }}
  default_browser_return_url: {{ include "ztka.consoleFQDNWithScheme" . }}
  selfservice_flows_settings_ui_url: {{ include "ztka.consoleFQDNWithScheme" . }}/ksettings
  selfservice_flows_recovery_ui_url: {{ include "ztka.consoleFQDNWithScheme" . }}/ksettings
  selfservice_flows_registration_ui_url: {{ include "ztka.consoleFQDNWithScheme" .}}/registeroidc
  selfservice_flows_error_ui_url: {{ include "ztka.consoleFQDNWithScheme" .}}/error-page
{{- end }}
