apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-server
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.relay "release" $.Release) | nindent 4 }}
    app.kubernetes.io/component: workload
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ztka.selectorLabels" (dict "image" $.Values.images.relay "release" $.Release) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ztka.labels" . | nindent 8 }}
        {{- include "ztka.selectorLabels" (dict "image" $.Values.images.relay "release" $.Release) | nindent 8 }}
        app.kubernetes.io/component: workload
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ztka.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: relay-audit-logs
          emptyDir: {}
      containers:
        - name: relay-tail
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag | default .Chart.AppVersion }}"
          args: ["--mode", "tail"]
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - name: relay-audit-logs
              mountPath: /audit-logs
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: relay-server-config
        - name: relay-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag | default .Chart.AppVersion }}"
          args: ["--mode", "server", "--log-level", "3"]
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - name: relay-audit-logs
              mountPath: /audit-logs
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: relay-server-config
          ports:
            {{- range .Values.services.relay.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
