{{- if .Values.deploy.contour.enable -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ztka-core-connector
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  virtualhost:
    fqdn: {{ include "ztka.coreConnectorFQDN" . | quote }}
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: relay-server
      port: 443
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ztka-user
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  virtualhost:
    fqdn: {{ include "ztka.userFQDN" . | quote }}
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: relay-server
      port: 443
{{- end -}}
