{{- if .Values.deploy.kratos.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: kratos
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  dsn: {{ include "ztka.dsn" . | b64enc | quote }}
  smtpConnectionURI: {{ .Values.deploy.kratos.smtpConnectionURI | b64enc | quote }}
{{- end }}
