{{- if .Values.deploy.postgresql.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{ end }}
