apiVersion: v1
kind: Service
metadata:
  name: prompt
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  type: {{ .Values.services.prompt.type }}
  ports:
    {{- range .Values.services.prompt.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port | default .containerPort }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 4 }}
