apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.paralus.name }}
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.paralus "release" $.Release) | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  type: {{ .Values.services.paralus.type }}
  ports:
    {{- range .Values.services.paralus.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port | default .containerPort }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.paralus "release" $.Release) | nindent 4 }}
