{{- if .Values.pgbouncer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-pgbouncer
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgbouncer
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: "{{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}"
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db" . }}
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db" . }}
                  key: password
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}-direct 
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db" . }}
                  key: database
            - name: POOL_MODE
              value: "{{ .Values.pgbouncer.poolMode }}"
            - name: MAX_CLIENT_CONN
              value: "{{ .Values.pgbouncer.maxClientConn }}"
            - name: DEFAULT_POOL_SIZE
              value: "{{ .Values.pgbouncer.defaultPoolSize }}"
            {{- range $key, $value := .Values.pgbouncer.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.pgbouncer.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
