
# @param {number} Number of replica pods to run 
replicaCount: 1

image:
  # @param {string} Docker image repository for GoAlert 
  repository: goalert/goalert
  # @param {string} Image pull policy for Kubernetes 
  pullPolicy: IfNotPresent
  # @param {string} Overrides the image tag. If empty, uses the chart appVersion 
  tag: ""

# @param {string[]} List of image pull secrets 
imagePullSecrets: []
# @param {string} Override the name of the chart 
nameOverride: ""
# @param {string} Override the full name of the chart 
fullnameOverride: ""

# @section GoAlert
goalert: 
  existingSecret:
    # @param {string} Name of an existing Kubernetes secret to use 
    name: ""
    keys:
      # @param {string} Key in the secret for the database URL 
      GOALERT_DB_URL: "GOALERT_DB_URL"
      # @param {string} Key in the secret for the data encryption key 
      GOALERT_DATA_ENCRYPTION_KEY: "GOALERT_DATA_ENCRYPTION_KEY"

  environment:
    # @param {string} Database URL for GoAlert 
    GOALERT_DB_URL: ""
    # @param {string} Data encryption key for GoAlert 
    GOALERT_DATA_ENCRYPTION_KEY: ""

postgresql:
    # @param {boolean} Whether to enable the bundled PostgreSQL database 
    enabled: true
    auth:
      # @param {string} Name of the database to create 
      database: goalert
      # @param {string} Username for the database 
      username: goalert
      # @param {string} Password for the database user 
      password: "example"
      # @param {string} SSL mode for database connection 
      sslmode: require
    service:
      # @param {number} Port on which PostgreSQL service is exposed 
      port: 5432

serviceAccount:
  # @param {boolean} Whether to create a service account 
  create: true
  # @param {object} Annotations to add to the service account 
  annotations: {}
  # @param {string} The name of the service account to use. If not set and create is true, a name is generated using the fullname template 
  name: ""

# @param {object} Annotations to add to the pod 
podAnnotations: {}

# @param {object} Security context for the pod 
podSecurityContext: {}
  # fsGroup: 2000

# @param {object} Security context for the container 
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # @param {string} Type of Kubernetes service to create 
  type: ClusterIP
  # @param {number} Port on which the service is exposed 
  port: 8081

ingress:
  # @param {boolean} Whether to create an Ingress resource 
  enabled: false
  # @param {string} Ingress class name 
  className: ""
  # @param {object} Annotations for the Ingress resource 
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # @param {object[]} List of hosts for the Ingress 
  hosts: []
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  # @param {object[]} TLS configuration for the Ingress 
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# @param {object} Resource requests and limits for the container 
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # @param {boolean} Whether to enable autoscaling 
  enabled: false
  # @param {number} Minimum number of replicas when autoscaling 
  minReplicas: 1
  # @param {number} Maximum number of replicas when autoscaling 
  maxReplicas: 100
  # @param {number} Target CPU utilization percentage for autoscaling 
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# @param {object} Node selector for pod assignment 
nodeSelector: {}

# @param {object[]} Tolerations for pod assignment 
tolerations: []

# @param {object} Affinity settings for pod assignment 
affinity: {}